### ISSUE TITLE
Win 10 support in the future?

### ISSUE THREAD

**Issue by thomhughes** [tandasat/PgResarch#3]
Are you ever planning on implementing windows 10 in this project?

**Comment by tandasat** [comment]
No, I do not have a concrete plan for it at this time, although I am certainly interested in the update. 

Note that I am discussing publishing more generic implementation for 8.1 as a sample to help others write their own disablers (The repo meow is supposed to be that one). That could be helpful for you.

**Comment by thomhughes** [comment]
Ok thanks :)
